live_config_reload = true

[font]
size = 12.0

[font.normal]
family = "Firacode Nerd Font"
style = "Regular"

[font.bold]
family = "Firacode Nerd Font"
style = "Bold"

[font.italic]
family = "Firacode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Firacode Nerd Font"
style = "Bold Italic"

[window]
padding = { x = 12, y = 12 }
decorations = "Full"
dynamic_padding = true
opacity = 1.0
dimensions = { columns = 95, lines = 25 }

[shell]
program = "C://WINDOWS//system32//wsl.exe -d Ubuntu"
args = ["--cd ~"]